#
# Podfile
# UnitTestingWithQuick
#

platform :ios, '13.0'

target 'Example-iOS' do
  use_frameworks!

  target 'Example-iOSTests' do
    inherit! :search_paths
    pod "Quick"
    pod "Nimble"
  end

  target 'Example-iOSUITests' do
  end
end
