#
# Podfile
# UnitTestingWithQuick
#

use_frameworks!


target 'Example-iOS' do
  platform :ios, '13.0'

  target 'Example-iOSTests' do
    inherit! :search_paths
    pod "Quick"
    pod "Nimble"
  end

  target 'Example-iOSUITests' do
  end
end

target 'Example-macOSFramework' do
  platform :macos, '10.15'

  target 'Example-macOSFrameworkTests' do
    inherit! :search_paths
    pod "Quick"
    pod "Nimble"
  end
end
